/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IProxyRegistry } from "../IProxyRegistry";

export class IProxyRegistry__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProxyRegistry {
    return new Contract(address, _abi, signerOrProvider) as IProxyRegistry;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "proxies",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
